server:
  port: 7870
  error:
    include-message: always

spring:
  application:
    name: forum-service
  main:
    allow-bean-definition-overriding: true
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
  profiles:
    active: ${PROFILE}