server:
  port: 7870
  error:
    include-message: always

spring:
  application:
    name: forum-service
  main:
    allow-bean-definition-overriding: true
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
  profiles:
    active: ${PROFILE}
  security:
    oauth2:
      resourceserver:
        id: ${BACKEND_AUDIENCE}
        jwk:
          jwk-set-uri: ${JWK_SET_URI}
          issuer-uri: ${ISSUER_URI}
  globalcors:
    corsConfiguration:
      '[/**]':
        allowedOrigins:
          - "http://localhost:3000"
          - "https://forum.joetymatthews.com"
        allowCredentials: true
        allowedHeaders:
          - Content-Type
          - Api-Type
          - Authorization
          - Set-Cookie
          - X-Requested-With
          - Cache-Control
        allowedMethods:
          - GET
          - POST
          - PUT
          - PATCH
          - DELETE
          - OPTIONS

auth0:
  uri: ${AUTH0_URI}
  client_id: ${CLIENT_ID}
  client_secret: ${CLIENT_SECRET}
  audience: ${AUTH_ID}
  backend_audience: ${BACKEND_AUDIENCE}
  backend_domain: ${BACKEND_DOMAIN}